language: cpp
compiler:
  - gcc
  - clang
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
install:
  # gcc 4.8
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -y -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -y -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  # libxzero dependencies
  - sudo apt-get install -y -qq cmake libgtest-dev pkg-config libtbb-dev libssl-dev libpcre3-dev
  - mkdir ~/gtest && cd ~/gtest && cmake /usr/src/gtest -DBUILD_SHARED_LIBS=ON && make && sudo cp -vp libgtest*.so /usr/local/lib/ && sudo ldconfig && cd -
script:
  - $CXX --version
  - cmake -DCMAKE_BUILD_TYPE=debug -DENABLE_{EXAMPLES,TESTS,PCRE}=ON
  - make
  - ./xzero-base/test-base
  - ./xzero-flow/test-flow
  - ./xzero-http/test-http
branches:
  only:
    - master
notifications:
  recipients:
    - trapni@gmail.com
  email:
    on_success: change
    on_failure: always
